<?php

namespace Database\Seeders;

use DB;
use Illuminate\Support\Str;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProjectReestrSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data_reesrt = [
            [
                'state' => "Планируемый",
                'location' => "Курская область",
                'title' =>"Создание биотехнологического комплекса по глубокой переработке пшеницы",
                'title_en' =>"Creation of a biotechnological complex for deep processing of wheat",
                'period' =>"2,5 года с начала финансирования (предварительно 2024 год)",
                'period_en' =>"2.5 years from the start of financing (pre-2024)",
                'price' =>"17 985",
                'investor' => "АО «ИннПромБиотех»",
                'investor_en' => "JSC «InnPromBiotech»",
                //'work_places' =>"",
                'description' => "ru_planned_1.html",
                'description_en' =>"en_planned_1.html",
                //'img' =>"",
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Планируемый",
                'location' => "Курская область",
                'title' =>"Строительство завода по глубокой переработке желтого гороха",
                'title_en' =>"Construction of a plant for deep processing of yellow peas",
                'period' =>"2023-2026",
                'period_en' =>"2023-2026",
                'price' =>"9282",
                'investor' => "ООО «Терра тех»",
                'investor_en' => "LLC «Terra Tech»",
                //'work_places' =>"",
                'description' => "ru_planned_2.html",
                'description_en' =>"en_planned_2.html",
                //'img' =>"",
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Планируемый",
                'location' => "Курская область",
                'title' =>"Строительство гостиничного комплекса «Здоровье» при ОБУЗ «КОНКЦ имени Г.Е. Островерхова»",
                'title_en' =>"Construction of the «Health» hotel complex at the Regional Educational Institution «Konkts” named after G.E. Ostroverkhova»",
                'period' =>"2019-2024",
                'period_en' =>"2019-2024",
                'price' =>"420",
                'investor' => "ООО «Гостиница «Здоровье»",
                'investor_en' => "LLC «Hotel Zdorovye»",
                //'work_places' =>"",
                'description' => "ru_planned_3.html",
                'description_en' =>"en_planned_3.html",
                //'img' =>"",
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Железногорск",
                'title' =>"Строительство завода по производству горячебрикетированного железа",
                'title_en' =>'Construction of a plant for the production of hot briquetted iron',
                'period' =>"2020-2024",
                'period_en' =>"2020-2024",
                'price' =>"47 567",
                'investor' => 'ООО «Михайловский ГБЖ»',
                'investor_en' => 'LLC "Mikhailovsky HBI"',
                'work_places' => "391",
                'description' => "ru_preparing_1.html",
                'description_en' =>"en_preparing_1.html",
                'img' =>["preparing_img_1.webp"],
                'presentation' => "preparing_presentation_1.pdf",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Железногорск",
                'title' =>"Строительство дробильно-конвейерного комплекса на северо-восточном и юго-восточном борту карьера",
                'title_en' =>'Construction of a crushing and conveyor complex on the northeastern and southeastern sides of the quarry',
                'period' =>"2014-2024",
                'period_en' =>"2014-2024",
                'price' =>"14 712",
                'investor' => 'АО «Михайловский ГОК им. А.В. Варичева',
                'investor_en' => 'JSC Mikhailovsky Mining and Processing Plant named after. A.V. Varicheva',
                'work_places' => "267",
                'description' => "ru_preparing_2.html",
                'description_en' =>"en_preparing_2.html",
                'img' =>["preparing_img_2_1.jpg","preparing_img_2_2.jpg","preparing_img_2_3.jpg","preparing_img_2_4.jpg"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курчатов",
                'title' =>"Строительство Курской АЭС-2 (станция замещения Курской АЭС). Энергоблоки N 1 и N 2",
                'title_en' =>'Construction of Kursk NPP-2 (replacement station for Kursk NPP). Power units N 1 and N 2',
                'period' =>"2012-2027",
                'period_en' =>"2012-2027",
                'price' =>"508 697",
                'investor' => 'Филиал АО «Концерн Росэнергоатом «Курская АЭС»',
                'investor_en' => 'Branch of Rosenergoatom Concern JSC Kursk NPP',
                'work_places' => "1359",
                'description' => "ru_preparing_3.html",
                'description_en' =>"en_preparing_3.html",
                'img' =>["preparing_img_3_1.webp","preparing_img_3_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курчатов",
                'title' =>"Комплекс переработки радиоактивных отходов Курской АЭС",
                'title_en' =>'Radioactive waste processing complex at Kursk NPP',
                'period' =>"2016-2024",
                'period_en' =>"2016-2024",
                'price' =>"25 062,01",
                'investor' => 'Филиал АО «Концерн Росэнергоатом «Курская АЭС»',
                'investor_en' => 'Branch of Rosenergoatom Concern JSC Kursk NPP',
                'work_places' => "598",
                'description' => "ru_preparing_4.html",
                'description_en' =>"en_preparing_4.html",
                'img' =>["preparing_img_4.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Реконструкция систем биологической очистки городских очистных сооружений",
                'title_en' =>'Radioactive waste processing complex at Kursk NPP',
                'period' =>"2019-2024",
                'period_en' =>"2019-2024",
                'price' =>"2838,465",
                'investor' => 'МУП «Курскводоканал»',
                'investor_en' => 'MUP "Kurskvodokanal"',
                //'work_places' => "",
                'description' => "ru_preparing_5.html",
                'description_en' =>"en_preparing_5.html",
                'img' =>["preparing_img_5_1.jpg", "preparing_img_5_2.jpg"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Реализация долгосрочной инвестиционной программы",
                'title_en' =>'Implementation of a long-term investment program',
                'period' =>"2018-2024",
                'period_en' =>"2018-2024",
                'price' =>"4 208",
                'investor' => 'Филиал ПАО «Россети Центр» — «Курскэнерго»',
                'investor_en' => 'Branch of PJSC "Rosseti Center" - "Kurskenergo"',
                //'work_places' => "",
                'description' => "ru_preparing_6.html",
                'description_en' =>"en_preparing_6.html",
                'img' =>["preparing_img_6_1.webp", "preparing_img_6_2.webp", "preparing_img_6_3.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Строительство 3х складских помещений, жомосушилки и свеклоподраздела емкостью 150 тыс. тонн свеклы",
                'title_en' =>'Construction of 3 warehouses, a pulp dryer and a beet subsection with a capacity of 150 thousand tons of beets',
                'period' =>"2016-2025",
                'period_en' =>"2016-2025",
                'price' =>"2 183,3",
                'investor' => 'ООО «КурскСахарПром» — филиал «Золотухинский»',
                'investor_en' => 'KurskSakharProm LLC - Zolotukhinsky branch"',
                'work_places' => "20",
                'description' => "ru_preparing_7.html",
                'description_en' =>"en_preparing_7.html",
                'img' =>["preparing_img_7.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Строительство селекционно-семеноводческого центра по созданию гибридов кукурузы, по производству семян родительских форм гибридов кукурузы, по производству семян кукурузы F1 в п. Камыши",
                'title_en' =>'Construction of a breeding and seed-growing center for the creation of corn hybrids, for the production of seeds of parental forms of corn hybrids, for the production of F1 corn seeds in the village of Kamyshi',
                'period' =>"2023-2026",
                'period_en' =>"2023-2026",
                'price' =>"2 792",
                'investor' => 'ООО «КурскАгроАктив»',
                'investor_en' => 'LLC "KurskAgroActive"',
                'work_places' => "106",
                'description' => "ru_preparing_8.html",
                'description_en' =>"en_preparing_8.html",
                'img' =>["preparing_img_8.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Беловский район",
                'title' =>"Закладка промышленного интенсивного безопорного яблоневого сада на 150 га",
                'title_en' =>'Construction of an industrial intensive unsupported apple orchard on 150 hectares',
                'period' =>"2016-2024",
                'period_en' =>"2016-2024",
                'price' =>"226",
                'investor' => 'ООО «Псельское»',
                'investor_en' => 'LLC "Pselskoe"',
                'work_places' => "137",
                'description' => "ru_preparing_9.html",
                'description_en' =>"en_preparing_9.html",
                'img' =>["preparing_img_9.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Беловский район",
                'title' =>"Строительство плодохранилища на 5000 тонн в Беловском районе Курской области на территории Малосолдатского сельсовета",
                'title_en' =>'Construction of a fruit storage facility for 5,000 tons in the Belovsky district of the Kursk region on the territory of the Malosoldatsky village council',
                'period' =>"2022-2024",
                'period_en' =>"2022-2024",
                'price' =>"563",
                'investor' => 'ООО «Псельское»',
                'investor_en' => 'LLC "Pselskoe"',
                'work_places' => "27",
                'description' => "ru_preparing_10.html",
                'description_en' =>"en_preparing_10.html",
                'img' =>["preparing_img_10.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Мантуровский район",
                'title' =>"Строительство плодохранилища",
                'title_en' =>'Construction of a fruit storage facility',
                'period' =>"2019-2024",
                'period_en' =>"2019-2024",
                'price' =>"620",
                'investor' => 'ООО «Луч»',
                'investor_en' => 'LLC "Luch"',
                'work_places' => "57",
                'description' => "ru_preparing_11.html",
                'description_en' =>"en_preparing_11.html",
                'img' =>["preparing_img_11_1.webp", "preparing_img_11_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Мантуровский район",
                'title' =>"Строительство молочно-товарной фермы на 2500 фуражных коров беспривязного содержания",
                'title_en' =>'Construction of a commercial dairy farm for 2,500 free-stall forage cows',
                'period' =>"2020-2024",
                'period_en' =>"2020-2024",
                'price' =>"1 455",
                'investor' => 'ООО «Луч»',
                'investor_en' => 'LLC "Luch"',
                'work_places' => "110",
                'description' => "ru_preparing_12.html",
                'description_en' =>"en_preparing_12.html",
                'img' =>["preparing_img_12_1.webp", "preparing_img_12_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Мантуровский район",
                'title' =>"Реконструкция молочно-товарной фермы на 1700 фуражных коров",
                'title_en' =>'Reconstruction of a dairy farm for 1,700 feed cows',
                'period' =>"2020-2024",
                'period_en' =>"2020-2024",
                'price' =>"153",
                'investor' => 'ООО «Луч»',
                'investor_en' => 'LLC "Luch"',
                'work_places' => "100",
                'description' => "ru_preparing_13.html",
                'description_en' =>"en_preparing_13.html",
                'img' =>["preparing_img_13_1.webp", "preparing_img_13_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Щигры",
                'title' =>"Строительство новых мощностей и реконструкция действующих, предназначенных для приемки, подработки, хранения и отгрузки зерна",
                'title_en' =>'Construction of new facilities and reconstruction of existing ones intended for acceptance, part-time work, storage and shipment of grain',
                'period' =>"2017-2024",
                'period_en' =>"2017-2024",
                'price' =>"3 500",
                'investor' => 'АО «Щигровский КХП»',
                'investor_en' => 'Shchigrovsky KHP JSC',
                'work_places' => "74",
                'description' => "ru_preparing_14.html",
                'description_en' =>"en_preparing_14.html",
                'img' =>["preparing_img_14.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Реконструкция склада бестарного хранения муки",
                'title_en' =>'Reconstruction of the bulk flour storage warehouse',
                'period' =>"2021-2025",
                'period_en' =>"2021-2025",
                'price' =>"80",
                'investor' => 'ОАО «Курскхлеб»',
                'investor_en' => 'JSC "Kurskkhleb"',
                //'work_places' => "",
                'description' => "ru_preparing_15.html",
                'description_en' =>"en_preparing_15.html",
                'img' =>["preparing_img_15.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Деревня Ворошнево, Курская область",
                'title' =>"Строительство селекционно-семеноводческого центра по производству различных видов семян сельскохозяйственных культур мощностью 43,5 тыс. тонн в год",
                'title_en' =>'Construction of a seed breeding center for the production of various types of agricultural seeds with a capacity of 43.5 thousand tons per year',
                'period' =>"2022-2024",
                'period_en' =>"2022-2024",
                'price' =>"3 500",
                'investor' => 'ООО «Мираторг-Курск»',
                'investor_en' => '"Miratorg-Kursk LLC"',
                'work_places' => "27",
                'description' => "ru_preparing_16.html",
                'description_en' =>"en_preparing_16.html",
                'img' =>["preparing_img_16.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализуемые",
                'location' => "Конышевский район",
                'title' =>"Реконструкция и модернизация мясохладобойни в п. Конышевка Курской области",
                'title_en' =>'Reconstruction and modernization of a meat and meat processing plant in Konyshevka village, Kursk region',
                'period' =>"2023-2024",
                'period_en' =>"2023-2024",
                'price' =>"4 349",
                'investor' => 'ООО «КУРСК АГРО ПРОДУКТ» (ГК «Агропромкомплектация»)',
                'investor_en' => 'KURSK AGRO PRODUCT LLC (Agropromkomplektatsiya Group of Companies)',
                'work_places' => "223",
                'description' => "ru_preparing_17.html",
                'description_en' =>"en_preparing_17.html",
                'img' =>["preparing_img_17_1.webp", "preparing_img_17_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
             
            [
                'state' => "Реализуемые",
                'location' => "Обоянский район",
                'title' =>"Строительство склада-холодильника на 5000 тысяч тонн",
                'title_en' =>'Construction of a refrigerator warehouse for 5,000 thousand tons',
                'period' =>"2021-2024",
                'period_en' =>"2021-2024",
                'price' =>"357",
                'investor' => 'ООО «Зоринский сад»',
                'investor_en' => 'LLC "Zorinsky garden"',
                'work_places' => "50",
                'description' => "ru_preparing_18.html",
                'description_en' =>"en_preparing_18.html",
                'img' =>["preparing_img_18_1.webp", "preparing_img_18_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Советский район",
                'title' =>"Строительство элеватора вместимостью 50 000 тысяч тонн",
                'title_en' =>'Construction of an elevator with a capacity of 50,000 thousand tons',
                'period' =>"2021-2024",
                'period_en' =>"2021-2024",
                'price' =>"158",
                'investor' => 'АО «Агрокомплекс «Мансурово»',
                'investor_en' => 'JSC "Agrocomplex "Mansurovo"',
                'work_places' => "29",
                'description' => "ru_preparing_19.html",
                'description_en' =>"en_preparing_19.html",
                'img' =>["preparing_img_19.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Организация участка по производству мягких желатиновых капсул",
                'title_en' =>'Organization of a site for the production of soft gelatin capsules',
                'period' =>"2022-2024",
                'period_en' =>"2022-2024",
                'price' =>"1156,4",
                'investor' => 'ОАО «Фармстандарт-Лексредства»',
                'investor_en' => 'JSC "Pharmstandard-Lexredstva"',
                //'work_places' => "",
                'description' => "ru_preparing_20.html",
                'description_en' =>"en_preparing_20.html",
                'img' =>["preparing_img_20.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Площадка для увеличения мощности производства трубопроводов и гусеничных лент",
                'title_en' =>'A platform for increasing the production capacity of pipelines and track belts',
                'period' =>"2020-2026",
                'period_en' =>"2020-2026",
                'price' =>"2800,0",
                'investor' => 'ООО НПО «Композит»',
                'investor_en' => 'NPO Composite LLC',
                'work_places' => "350",
                'description' => "ru_preparing_21.html",
                'description_en' =>"en_preparing_21.html",
                'img' =>["preparing_img_21_1.webp","preparing_img_21_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Производство полиэфирной нити",
                'title_en' =>'Production of polyester yarn',
                'period' =>"2019-2024",
                'period_en' =>"2019-2024",
                'price' =>"2300",
                'investor' => 'ООО «Союзтекстиль-СТ»',
                'investor_en' => 'Soyuztextil-ST LLC',
                'work_places' => "100",
                'description' => "ru_preparing_22.html",
                'description_en' =>"en_preparing_22.html",
                'img' =>["preparing_img_22_1.webp","preparing_img_22_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Железногорский район",
                'title' =>"Производство полиэфира на основе демитилрефлата",
                'title_en' =>'Production of polyester based on demitylreflate',
                'period' =>"2023-2026",
                'period_en' =>"2023-2026",
                'price' =>"240",
                'investor' => 'ООО «Передовые технологии машиностроения»',
                'investor_en' => 'Advanced Engineering Technologies LLC',
                'work_places' => "70",
                'description' => "ru_preparing_23.html",
                'description_en' =>"en_preparing_23.html",
                'img' =>["preparing_img_23_1.webp","preparing_img_23_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Железногорский район",
                'title' =>"Строительство завода по производству резинотехнических изделий",
                'title_en' =>'Construction of a factory for the production of rubber products',
                'period' =>"2023-2025",
                'period_en' =>"2023-2025",
                'price' =>"168",
                'investor' => 'ООО «Железногорский завод РТИ»',
                'investor_en' => 'Zheleznogorsk RTI Plant LLC',
                'work_places' => "53",
                'description' => "ru_preparing_24.html",
                'description_en' =>"en_preparing_24.html",
                'img' =>["preparing_img_24.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Железногорский район",
                'title' =>"Строительство завода по производству вельц-оксида цинка",
                'title_en' =>'Construction of a plant for the production of zinc oxide',
                'period' =>"2022-2024",
                'period_en' =>"2022-2024",
                'price' =>"10 800",
                'investor' => 'ООО «Цинкум»',
                'investor_en' => 'LLC "Zinkum"',
                'work_places' => "72",
                'description' => "ru_preparing_25.html",
                'description_en' =>"en_preparing_25.html",
                'img' =>["preparing_img_25_1.webp","preparing_img_25_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Железногорский район",
                'title' =>"Проект организации современного производственного комплекса для выпуска инновационной железнодорожной техники",
                'title_en' =>'The project of organizing a modern production complex for the production of innovative railway equipment',
                'period' =>"2023-2025",
                'period_en' =>"2023-2025",
                'price' =>"234",
                'investor' => 'ООО «Передовые технологии машиностроения»',
                'investor_en' => 'Advanced Engineering Technologies LLC',
                'work_places' => "40",
                'description' => "ru_preparing_26.html",
                'description_en' =>"en_preparing_26.html",
                'img' =>["preparing_img_26.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Разработка и организация серийного производства генераторов и электроустановок мощностью 900-1600 кВт",
                'title_en' =>'Development and organization of serial production of generators and electrical installations with a capacity of 900-1600 kW',
                'period' =>"2019-2025",
                'period_en' =>"2019-2025",
                'price' =>"102",
                'investor' => 'ОАО «Электроагрегат»',
                'investor_en' => 'JSC "Electroagregat"',
                //'work_places' => "",
                'description' => "ru_preparing_27.html",
                'description_en' =>"en_preparing_27.html",
                'img' =>["preparing_img_27_1.webp","preparing_img_27_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Многопрофильная областная детская клиническая больница 3-го уровня",
                'title_en' =>"Multidisciplinary regional children's Clinical hospital of the 3rd level",
                'period' =>"2021-2026",
                'period_en' =>"2021-2026",
                'price' =>"8245,024",
                'investor' => 'Правительство Курской области',
                'investor_en' => 'The Government of the Kursk region',
                //'work_places' => "",
                'description' => "ru_preparing_28.html",
                'description_en' =>"en_preparing_28.html",
                'img' =>["preparing_img_28.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Строительство общеобразовательной школы на 1600 мест по проспекту Н. Плевицкой",
                'title_en' =>"Construction of a comprehensive school for 1600 places on N. Plevitskaya Avenue",
                'period' =>"2023-2032",
                'period_en' =>"2023-2032",
                'price' =>"4100",
                'investor' => 'Правительство Курской области',
                'investor_en' => 'The Government of the Kursk region',
                //'work_places' => "",
                'description' => "ru_preparing_29.html",
                'description_en' =>"en_preparing_29.html",
                'img' =>["preparing_img_29.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Обновление городского электрического транспорта",
                'title_en' =>"Urban electric transport upgrade",
                'period' =>"2022-2024",
                'period_en' =>"2022-2024",
                'price' =>"12 941",
                'investor' => 'Правительство Курской области',
                'investor_en' => 'The Government of the Kursk region',
                //'work_places' => "",
                'description' => "ru_preparing_30.html",
                'description_en' =>"en_preparing_30.html",
                'img' =>["preparing_img_30_1.webp","preparing_img_30_2.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Строительство жилого района «Северный»",
                'title_en' =>'Construction of the residential area "Severny"',
                'period' =>"2010-2024",
                'period_en' =>"2010-2024",
                'price' =>"9 800",
                'investor' => 'АО «Курский завод КПД им. А.Ф. Дериглазова»',
                'investor_en' => 'JSC Kursk Plant of Efficiency named after A.F. Deriglazov',
                //'work_places' => "",
                'description' => "ru_preparing_31.html",
                'description_en' =>"en_preparing_31.html",
                'img' =>["preparing_img_31.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Город Курск",
                'title' =>"Строительство гостиничного комплекса «Здоровье» при ОБУЗ «КОНКЦ имени Г.Е. Островерхова»",
                'title_en' =>'Construction of the hotel complex "Zdorovye" at the OBUZ "KONKTS named after G.E. Ostroverkhov"',
                'period' =>"2019-2024",
                'period_en' =>"2019-2024",
                'price' =>"420",
                'investor' => 'ООО «Гостиница «Здоровье»',
                'investor_en' => 'LLC "Hotel "Health"',
                'work_places' => "26",
                'description' => "ru_preparing_32.html",
                'description_en' =>"en_preparing_32.html",
                'img' =>["preparing_img_32.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Строительство магазинов торговой сети «Пятерочка»",
                'title_en' =>'Construction of stores of the Pyaterochka retail chain',
                'period' =>"2023-2025",
                'period_en' =>"2023-2025",
                'price' =>"350",
                'investor' => 'ООО «Агроторг» и ООО «ТС5»',
                'investor_en' => 'Agrotorg LLC and TS5 LLC',
                //'work_places' => "",
                'description' => "ru_preparing_33.html",
                'description_en' =>"en_preparing_33.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Строительство магазинов торговой сети «Магнит»",
                'title_en' =>'Construction of stores of the Magnit retail chain',
                'period' =>"2023-2025",
                'period_en' =>"2023-2025",
                'price' =>"300",
                'investor' => 'АО «Тандер»',
                'investor_en' => 'JSC "Thunder"',
                //'work_places' => "",
                'description' => "ru_preparing_34.html",
                'description_en' =>"en_preparing_34.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализуемые",
                'location' => "Курская область",
                'title' =>"Строительство автоматизированного мусоросортировочного комплекса",
                'title_en' =>'Construction of an automated waste sorting complex',
                'period' =>"2023-2025",
                'period_en' =>"2023-2025",
                'price' =>"2 102",
                'investor' => 'ООО «Флагман-Курск»',
                'investor_en' => 'LLC "Flagship-Kursk"',
                //'work_places' => "",
                'description' => "ru_preparing_35.html",
                'description_en' =>"en_preparing_35.html",
                'img' =>["preparing_img_35.webp"],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Строительство цеха по производству сыров твердых сортов и творога",
                'title_en' =>'Construction of a workshop for the production of hard cheeses and cottage cheese',
                'period' =>"2015-2020",
                'period_en' =>"2015-2020",
                'price' =>"320",
                'investor' => 'ООО «Курское молоко»',
                'investor_en' => 'Kursk Milk LLC',
                //'work_places' => "",
                'description' => "ru_realized_1.html",
                'description_en' =>"en_realized_1.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Строительство цеха по производству сыров твердых сортов и творога",
                'title_en' =>'Construction of a workshop for the production of hard cheeses and cottage cheese',
                'period' =>"2018-2020",
                'period_en' =>"2018-2020",
                'price' =>"920",
                'investor' => 'ООО «Грейнрус Агро»',
                'investor_en' => 'Greinrus Agro LLC',
                //'work_places' => "",
                'description' => "ru_realized_2.html",
                'description_en' =>"en_realized_2.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Строительство свиноводческих комплексов",
                'title_en' =>'Construction of pig breeding complexes',
                'period' =>"2017-2024",
                'period_en' =>"2017-2024",
                'price' =>"94000",
                'investor' => 'ООО «Мираторг-Курск»',
                'investor_en' => 'Miratorg-Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_3.html",
                'description_en' =>"en_realized_3.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Замещение импортируемого желатина и коллагена",
                'title_en' =>'Substitution of imported gelatin and collagen',
                'period' =>"2021-2023",
                'period_en' =>"2021-2023",
                'price' =>"5780",
                'investor' => 'ООО «АПХ Мираторг» и ООО «Мираторг-Желатин»',
                'investor_en' => 'LLC "APH Miratorg" and LLC "Miratorg-Gelatin"',
                //'work_places' => "",
                'description' => "ru_realized_4.html",
                'description_en' =>"en_realized_4.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Производство начальной формы фармацевтического гепарина и кормового концентрированного протеина путем глубокой переработки побочной продукции свиноводства",
                'title_en' =>'Production of the initial form of pharmaceutical heparin and feed concentrated protein by deep processing of pig by-products',
                'period' =>"2021-2023",
                'period_en' =>"2021-2023",
                'price' =>"1850",
                'investor' => 'ООО «АПХ Мираторг» и ООО «Гепаринус»',
                'investor_en' => 'LLC "APH Miratorg" and LLC "Heparinus"',
                //'work_places' => "",
                'description' => "ru_realized_5.html",
                'description_en' =>"en_realized_5.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
       
            [
                'state' => "Реализованный",
                'location' => "Курский район",
                'title' =>"Селекционно-семеноводческий центр по производству семян сельскохозяйственных культур",
                'title_en' =>'Seed breeding center for the production of agricultural seeds',
                'period' =>"2022-2023",
                'period_en' =>"2022-2023",
                'price' =>"850",
                'investor' => 'ООО «Мираторг-Курск»',
                'investor_en' => 'Miratorg-Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_6.html",
                'description_en' =>"en_realized_6.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Строительство производственно-логистического комплекса «Курскагротерминал",
                'title_en' =>'Construction of the Kurskagroterminal production and logistics complex',
                'period' =>"2019-2023",
                'period_en' =>"2019-2023",
                'price' =>"38600",
                'investor' => 'ООО «Курскагротерминал»',
                'investor_en' => 'Kurskagroterminal LLC',
                //'work_places' => "",
                'description' => "ru_realized_7.html",
                'description_en' =>"en_realized_7.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Закладка сада интенсивного типа и реконструкция фруктохранилища",
                'title_en' =>'Laying of an intensive type garden and reconstruction of a fruit storage',
                'period' =>"2016-2022",
                'period_en' =>"2016-2022",
                'price' =>"229",
                'investor' => 'ООО «Зоринский сад»',
                'investor_en' => 'LLC "Zorinsky garden"',
                //'work_places' => "",
                'description' => "ru_realized_8.html",
                'description_en' =>"en_realized_8.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Реконструкция комбикормового завода",
                'title_en' =>'Reconstruction of the feed mill',
                'period' =>"2016-2020",
                'period_en' =>"2016-2020",
                'price' =>"315",
                'investor' => 'ООО «Щигровский КХП»',
                'investor_en' => 'Shchigrovsky KHP LLC',
                //'work_places' => "",
                'description' => "ru_realized_9.html",
                'description_en' =>"en_realized_9.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Железногорский район",
                'title' =>"Строительство в Железногорском районе животноводческого комплекса молочного направления",
                'title_en' =>'Construction of a dairy livestock complex in Zheleznogorsk district',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"4507",
                'investor' => 'ООО «Агропромкомплектация Курск»',
                'investor_en' => 'Agropromkomplektatsiya Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_10.html",
                'description_en' =>"en_realized_10.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                'location' => "Дмитриевский район",
                'title' =>"Строительство в Дмитриевском районе животноводческого комплекса молочного направления",
                'title_en' =>'Construction of a dairy livestock complex in Dmitrievsky district',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"8550",
                'investor' => 'ООО «Агропромкомплектация Курск»',
                'investor_en' => 'Agropromkomplektatsiya Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_11.html",
                'description_en' =>"en_realized_11.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
                        
            [
                'state' => "Реализованный",
                'location' => "Железногорский район",
                'title' =>"Строительство в Железногорском районе специализированной фермы",
                'title_en' =>'Construction of a specialized farm in Zheleznogorsk district',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"1028",
                'investor' => 'ООО «Агропромкомплектация Курск»',
                'investor_en' => 'Agropromkomplektatsiya Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_12.html",
                'description_en' =>"en_realized_12.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Реконструкция и модернизация имеющихся производственных площадок",
                'title_en' =>'Reconstruction and modernization of existing production sites',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"2608",
                'investor' => 'ООО «Агропромкомплектация Курск»',
                'investor_en' => 'Agropromkomplektatsiya Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_13.html",
                'description_en' =>"en_realized_13.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Развитие свиноводства",
                'title_en' =>'Development of pig farming',
                'period' =>"2022-2023",
                'period_en' =>"2022-2023",
                'price' =>"2868",
                'investor' => 'ООО «Агропромкомплектация Курск»',
                'investor_en' => 'Agropromkomplektatsiya Kursk LLC',
                //'work_places' => "",
                'description' => "ru_realized_14.html",
                'description_en' =>"en_realized_14.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Строительство комплекса по производству культивируемых грибов шампиньонов на собственном компосте",
                'title_en' =>'Construction of a complex for the production of cultivated mushrooms on its own compost',
                'period' =>"2019-2023",
                'period_en' =>"2019-2023",
                'price' =>"9800",
                'investor' => 'ООО «Грибная радуга»',
                'investor_en' => 'Mushroom Rainbow LLC',
                //'work_places' => "",
                'description' => "ru_realized_15.html",
                'description_en' =>"en_realized_15.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Создание плодохранилища",
                'title_en' =>'Creation of a fruit storage facility',
                'period' =>"2021-2022",
                'period_en' =>"2021-2022",
                'price' =>"1100",
                'investor' => 'ООО «Зоринский сад»',
                'investor_en' => 'LLC "Zorinsky garden"',
                //'work_places' => "",
                'description' => "ru_realized_16.html",
                'description_en' =>"en_realized_16.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Закладка яблоневого сада",
                'title_en' =>'Creation of a fruit storage facility',
                'period' =>"2020-2022",
                'period_en' =>"2020-2022",
                'price' =>"520",
                'investor' => 'ООО «Луч»',
                'investor_en' => 'LLC "Luch"',
                //'work_places' => "",
                'description' => "ru_realized_17.html",
                'description_en' =>"en_realized_17.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                'location' => "Беловский район",
                'title' =>"Строительство молочно-товарной фермы на 1800 фуражных коров",
                'title_en' =>'Construction of a dairy farm for 1800 feed cows',
                'period' =>"2021-2023",
                'period_en' =>"2021-2023",
                'price' =>"1174",
                'investor' => 'ООО «Псёльское»',
                'investor_en' => 'LLC "Pselskoe"',
                //'work_places' => "",
                'description' => "ru_realized_18.html",
                'description_en' =>"en_realized_18.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
                        
            [
                'state' => "Реализованный",
                'location' => "Город Курск",
                'title' =>"Реконструкция производства жидких лекарственных форм",
                'title_en' =>'Reconstruction of the production of liquid dosage forms',
                'period' =>"2018-2020",
                'period_en' =>"2018-2020",
                'price' =>"234",
                'investor' => 'ОАО «Фармстандарт-Лексредства»',
                'investor_en' => 'JSC "Pharmstandard-Lexredstva"',
                //'work_places' => "",
                'description' => "ru_realized_19.html",
                'description_en' =>"en_realized_19.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
                         
            [
                'state' => "Реализованный",
                'location' => "Город Курск",
                'title' =>"Реконструкция цеха №17",
                'title_en' =>'Reconstruction of workshop No. 17',
                'period' =>"2021-2023",
                'period_en' =>"2021-2023",
                'price' =>"2200",
                'investor' => 'ОАО «Фармстандарт-Лексредства»',
                'investor_en' => 'JSC "Pharmstandard-Lexredstva"',
                //'work_places' => "",
                'description' => "ru_realized_20.html",
                'description_en' =>"en_realized_20.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Город Курск",
                'title' =>"Реконструкция цеха №2",
                'title_en' =>'Reconstruction of workshop No. 2',
                'period' =>"2018-2023",
                'period_en' =>"2018-2023",
                'price' =>"2200",
                'investor' => 'ОАО «Фармстандарт-Лексредства»',
                'investor_en' => 'JSC "Pharmstandard-Lexredstva"',
                //'work_places' => "",
                'description' => "ru_realized_21.html",
                'description_en' =>"en_realized_21.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
            
            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Освоение производства новых медицинских изделий",
                'title_en' =>'Mastering the production of new medical devices',
                'period' =>"2015-2020",
                'period_en' =>"2015-2020",
                'price' =>"1500",
                'investor' => 'ООО «Эскулап»',
                'investor_en' => 'LLC "Aesculapius"',
                //'work_places' => "",
                'description' => "ru_realized_22.html",
                'description_en' =>"en_realized_22.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                //'location' => "",
                'title' =>"Установка нового оборудования для сборки резинотросового полотна на линии ЛСО РТЛ-2400",
                'title_en' =>'Installation of new equipment for the assembly of a rubber sheet on the LSO RTL-2400 line',
                'period' =>"2021",
                'period_en' =>"2021",
                'price' =>"70,45",
                'investor' => 'ОАО «Курскрезинотехника»',
                'investor_en' => 'JSC "Kurskrezinotekhnika"',
                //'work_places' => "",
                'description' => "ru_realized_23.html",
                'description_en' =>"en_realized_23.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация каландра №101",
                'title_en' =>'Modernization of the calender No. 101',
                'period' =>"2019-2021",
                'period_en' =>"2019-2021",
                'price' =>"247,55",
                'investor' => 'ОАО «Курскрезинотехника»',
                'investor_en' => 'JSC "Kurskrezinotekhnika"',
                //'work_places' => "",
                'description' => "ru_realized_24.html",
                'description_en' =>"en_realized_24.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация пресса № 3",
                'title_en' =>'Modernization of press No. 3',
                'period' =>"2021",
                'period_en' =>"2021",
                'price' =>"46,81",
                'investor' => 'ОАО «Курскрезинотехника»',
                'investor_en' => 'JSC "Kurskrezinotekhnika"',
                //'work_places' => "",
                'description' => "ru_realized_25.html",
                'description_en' =>"en_realized_25.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Замена МЛ924 и МнЛ616 на EVOL 100/350",
                'title_en' =>'Replacing ML924 and MnL616 with EVOL 100/350',
                'period' =>"2021-2022",
                'period_en' =>"2021-2022",
                'price' =>"318,5",
                'investor' => 'ОАО «Курскрезинотехника»',
                'investor_en' => 'JSC "Kurskrezinotekhnika"',
                //'work_places' => "",
                'description' => "ru_realized_26.html",
                'description_en' =>"en_realized_26.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация печатной машины Flexpress-10 и 8",
                'title_en' =>'Modernization of the Flexpress-10 and 8 printing press',
                'period' =>"2019-2020",
                'period_en' =>"2019-2020",
                'price' =>"20",
                'investor' => 'АО «Полипак»',
                'investor_en' => 'JSC "Polypak"',
                //'work_places' => "",
                'description' => "ru_realized_27.html",
                'description_en' =>"en_realized_27.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация и техническое перевооружение производства",
                'title_en' =>'Modernization and technical re-equipment of production',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"302",
                'investor' => 'АО «Полипак»',
                'investor_en' => 'JSC "Polypak"',
                //'work_places' => "",
                'description' => "ru_realized_28.html",
                'description_en' =>"en_realized_28.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Замена гофропресса на агрегате BHS-5",
                'title_en' =>'Replacement of the corrugated press on the BHS-5 unit',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"232,26",
                'investor' => 'АО «ГОТЭК»',
                'investor_en' => 'JSC "GOTEK"',
                //'work_places' => "",
                'description' => "ru_realized_29.html",
                'description_en' =>"en_realized_29.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Увеличение объемов производства СБЕ-3",
                'title_en' =>'Increase in production volumes of SBE-3',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"378,51",
                'investor' => 'АО «ГОТЭК ПОЛИПАК»',
                'investor_en' => 'JSC "GOTEK POLYPAK"',
                //'work_places' => "",
                'description' => "ru_realized_30.html",
                'description_en' =>"en_realized_30.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Техническое перевооружение паросилового цеха",
                'title_en' =>'Technical re-equipment of the steam power plant',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"16",
                'investor' => 'АО «Изоплит»',
                'investor_en' => 'Izoplit JSC',
                //'work_places' => "",
                'description' => "ru_realized_31.html",
                'description_en' =>"en_realized_31.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Организация серийного производства микроэлектронных изделий специального использования",
                'title_en' =>'Organization of mass production of microelectronic products for special use',
                'period' =>"2020-2024",
                'period_en' =>"2020-2024",
                'price' =>"110",
                'investor' => 'ООО «Совтест АТЕ»',
                'investor_en' => 'Sovtest ATA LLC',
                //'work_places' => "",
                'description' => "ru_realized_32.html",
                'description_en' =>"en_realized_32.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Строительство завода по производству современных радиоэлектронных и МЭМС компонентов, изделий и аппаратуры, в том числе для систем мониторинга и измерений различного назначения",
                'title_en' =>'Construction of a plant for the production of modern radio-electronic and MEMS components, products and equipment, including for monitoring and measurement systems for various purposes',
                'period' =>"2015-2021",
                'period_en' =>"2015-2021",
                'price' =>"600",
                'investor' => 'ООО «Совтест АТЕ»',
                'investor_en' => 'Sovtest ATA LLC',
                //'work_places' => "",
                'description' => "ru_realized_33.html",
                'description_en' =>"en_realized_33.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Железногорский район",
                'title' =>"Модернизация и техническое перевооружение производства",
                'title_en' =>'Modernization and technical re-equipment of production',
                'period' =>"2019-2020",
                'period_en' =>"2019-2020",
                'price' =>"150",
                'investor' => 'ООО ПО «Вагонмаш»',
                'investor_en' => 'Vagonmash Software LLC',
                //'work_places' => "",
                'description' => "ru_realized_34.html",
                'description_en' =>"en_realized_34.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация производства для выпуска новой продукции — мебельного крепежа: винтов-конфирматов и стяжек эксцентриковых с целью импортозамещения на российском рынке",
                'title_en' =>'Modernization of production for the production of new products — furniture fasteners: confirmation screws and eccentric screeds for the purpose of import substitution in the Russian market',
                'period' =>"2019-2021",
                'period_en' =>"2019-2021",
                'price' =>"56,5",
                'investor' => 'ООО «Комплект»',
                'investor_en' => 'Kit LLC',
                //'work_places' => "",
                'description' => "ru_realized_35.html",
                'description_en' =>"en_realized_35.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Освоение выпуска больших отбойных причальных приспособлений",
                'title_en' =>'Mastering the production of large jackhammer mooring devices',
                'period' =>"2018-2022",
                'period_en' =>"2018-2022",
                'price' =>"130",
                'investor' => 'ООО «РПИ КурскПром»',
                'investor_en' => 'LLC RPI KurskProm',
                //'work_places' => "",
                'description' => "ru_realized_36.html",
                'description_en' =>"en_realized_36.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Модернизация действующего производства",
                'title_en' =>'Modernization of existing production',
                'period' =>"2020-2021",
                'period_en' =>"2020-2021",
                'price' =>"109",
                'investor' => 'ООО «Акватон»',
                'investor_en' => 'Aquaton LLC',
                //'work_places' => "",
                'description' => "ru_realized_37.html",
                'description_en' =>"en_realized_37.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область, город Курск",
                'title' =>"Расширение ассортимента выпускаемых изделий АО «КЭАЗ»",
                'title_en' =>'Expanding the range of products manufactured by JSC "KEAZ"',
                'period' =>"2016-2021",
                'period_en' =>"2016-2021",
                'price' =>"636",
                'investor' => 'АО «КЭАЗ»',
                'investor_en' => 'JSC "KEAZ"',
                //'work_places' => "",
                'description' => "ru_realized_38.html",
                'description_en' =>"en_realized_38.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Развитие производства стартерных свинцово-кислотных батарей с применением пластмассовых комплектующих собственного изготовления",
                'title_en' =>'Development of production of starter lead-acid batteries using plastic components of own manufacture',
                'period' =>"2017-2023",
                'period_en' =>"2017-2023",
                'price' =>"455",
                'investor' => 'ООО «ИСТОК+»',
                'investor_en' => 'ISTOK+ LLC',
                //'work_places' => "",
                'description' => "ru_realized_39.html",
                'description_en' =>"en_realized_39.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курская область",
                'title' =>"Расширение номенклатуры выпускаемой продукции",
                'title_en' =>'Expansion of the product range',
                'period' =>"2016-2020",
                'period_en' =>"2016-2020",
                'price' =>"171",
                'investor' => 'ОАО «Электроагрегат»',
                'investor_en' => 'JSC "Electroagregat"',
                //'work_places' => "",
                'description' => "ru_realized_40.html",
                'description_en' =>"en_realized_40.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Железногорский район",
                'title' =>"Техническое перевооружение ДОК",
                'title_en' =>'Technical re-equipment of the DOCK',
                'period' =>"2016-2020",
                'period_en' =>"2016-2020",
                'price' =>"171",
                'investor' => 'АО «Михайловский ГОК им. А.В. Варичева»',
                'investor_en' => 'JSC Mikhailovsky GOK named after A.V. Varichev',
                //'work_places' => "",
                'description' => "ru_realized_41.html",
                'description_en' =>"en_realized_41.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Глушковский район",
                'title' =>"Строительство спортивно-оздоровительного комплекса в п. Глушково",
                'title_en' =>'Construction of a sports and recreation complex in the village of Glushkovo',
                'period' =>"2018-2020",
                'period_en' =>"2018-2020",
                'price' =>"160",
                'investor' => 'ПАО «Газпром»',
                'investor_en' => 'Gazprom PJSC',
                //'work_places' => "",
                'description' => "ru_realized_42.html",
                'description_en' =>"en_realized_42.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Суджанский район",
                'title' =>"Строительство физкультурно-оздоровительного комплекса с крытым катком",
                'title_en' =>'Construction of a sports and recreation complex with an indoor skating rink',
                'period' =>"2018-2020",
                'period_en' =>"2018-2020",
                'price' =>"190",
                'investor' => 'ПАО «Газпром»',
                'investor_en' => 'Gazprom PJSC',
                //'work_places' => "",
                'description' => "ru_realized_43.html",
                'description_en' =>"en_realized_43.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],

            [
                'state' => "Реализованный",
                'location' => "Курский район",
                'title' =>"Строительство «Распределительный центр «Курский»",
                'title_en' =>'Construction of the Kursky Distribution Center',
                'period' =>"2019-2021",
                'period_en' =>"2019-2021",
                'price' =>"1730",
                'investor' => 'ООО «Оператор»',
                'investor_en' => 'Operator LLC',
                //'work_places' => "",
                'description' => "ru_realized_44.html",
                'description_en' =>"en_realized_44.html",
                //'img' =>[""],
                //'presentation' => "",
                //'seo_title' => "",
                //'seo_description' => ""
            ],
        ];

        foreach ($data_reesrt as $item) {

            $directory = "planed";

            if ($item['state'] === "Реализуемые") $directory = "preparing";
            if ($item['state'] === "Реализованный") $directory = "realiz";

            $item['slug'] = Str::slug($item['title']);

            if (isset($item['img']) && !empty($item['img'])) {
                Storage::disk('public')->put("project_reestr/".$item['img'][0], file_get_contents(public_path('old_data/reestr_info/img_reestr/'.$item['img'][0])), 'public');
                $item['img'] = $item['img'][0];
            }
            if (isset($item['description']) && !empty($item['description'])) {
            $item['description'] = file_get_contents(public_path('old_data/reestr_info/'.$directory.'/'.$item['description']));
            $item['description_en'] = file_get_contents(public_path('old_data/reestr_info/'.$directory.'/'.$item['description_en']));
            }
            DB::table("project_reestrs")->insert(
                $item
            );
        }
    }
}
