<?php
$support_measures = [
  
    [
        'title' => "Льгота по налогу на имущество организаций",
        'title_en' => "Corporate property tax benefit",
        'type' => "Финансовая поддержка инвестора",
        'img' => "e12fjw9bpmk-159ceb12.webp",
        'inner_img' => "nalog-na-im-vo-57a71c6f.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление льготы по налогу на имущество организаций",
        'seo_description' => "Льготы по налогу на имущество организаций в Курской области предоставляются в соответствии с законодательством Российской Федерации и региональными нормативными актами.",
    ],

    [
        'title' => "Предоставление пониженных ставок по налогу на прибыль организации",
        'title_en' => "Provision of reduced corporate income tax rates",
        'type' => "Финансовая поддержка инвестора",
        'img' => "nkspwim0nvq-605263a4.webp",
        'inner_img' => "nalog-na-pribyl.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление пониженных ставок по налогу на прибыль организации",
        'seo_description' => "В Курской области, как и в большинстве регионов России, действуют пониженные ставки по налогу на прибыль организаций. Это означает, что вместо стандартной ставки в 20% (17% в федеральный бюджет и 3% в региональный бюджет), организации могут платить меньше.",
    ],

    [
        'title' => "Инвестиционный налоговый вычет",
        'title_en' => "Provision of reduced corporate income tax rates",
        'type' => "Финансовая поддержка инвестора",
        'img' => "jpvxudpuoyw-84b71b7a.webp",
        'inner_img' => "investiczionnyj-nalogovyj-vychet.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление инвестиционного налогового вычета",
        'seo_description' => "Инвестиционный налоговый вычет позволяет инвесторам уменьшить сумму налога на прибыль, уплачиваемого в бюджет, на сумму инвестиций в основные средства.",
    ],

    [
        'title' => "Предоставление субсидий на возмещение процентов по кредитам",
        'title_en' => "Provision of subsidies for repayment of interest on loans",
        'type' => "Финансовая поддержка инвестора",
        'img' => "sheto9r5ln0-611bbde3.webp",
        'inner_img' => "subsidii-na-vozmeshhenie-kreditov.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление инвестиционного налогового вычета",
        'seo_description' => "В Курской области для инвесторов предусмотрены различные меры поддержки, включая предоставление субсидий на возмещение процентов по кредитам.",
    ],

    [
        'title' => "Инвестиционный фонд Курской области",
        'title_en' => "Investment Fund of the Kursk region",
        'type' => "Финансовая поддержка инвестора",
        'img' => "lry7nbswuuk-3fe55a0a.webp",
        'inner_img' => "investiczionnyj-fond-kursk.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Инвестиционный фонд Курской области",
        'seo_description' => "Инвестиционный фонд Курской области — это организация, которая занимается привлечением инвестиций в регион. Он был создан для того, чтобы помочь развитию",
    ],

    [
        'title' => "Предоставление земельных участков на льготных условиях",
        'title_en' => "Provision of land plots on preferential terms",
        'type' => "Не финансовая поддержка инвестора",
        'img' => "park-yubilejnyj-pyaterochka-a9a59151.webp",
        'inner_img' => "zemelnye-uchastki-350f6392.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        'short_description_en' =>"en_short_description.html",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление земельных участков на льготных условиях",
        'seo_description' => "В соответствии с положениями ст. 39.6 Земельного кодекса РФ был принят закон Курской области от 22 июня 2015 года № 58-ЗКО «Об установлении критериев, которым",
    ],

    [
        'title' => "Льгота по налогу на имущество для резидентов ОЭЗ «Третий полюс»",
        'title_en' => "Property tax benefit for residents of the SEZ «Third Pole»",
        'type' => "Резидентам ОЭЗ «Третий полюс»",
        //'img' => "",
        //'inner_img' => "",
        //'inner_img_en' => "",
        'short_description' => "",
        //'short_description_en' =>"",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Льгота по налогу на имущество для резидентов ОЭЗ «Третий полюс»",
        'seo_description' => "Освобождение от уплаты  налога на имущество организаций — резидентов особой экономической зоны  в течение десяти лет с месяца, следующего за месяцем постановки на учет  имущества.",
    ],

    [
        'title' => "Льгота по транспортному налогу для резидентов ОЭЗ «Третий полюс»",
        'title_en' => "Transport tax benefit for residents of the SEZ «Third Pole»",
        'type' => "Резидентам ОЭЗ «Третий полюс»",
        //'img' => "",
        //'inner_img' => "",
        //'inner_img_en' => "",
        'short_description' => "",
        //'short_description_en' =>"",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Льгота по транспортному налогу для резидентов ОЭЗ «Третий полюс»",
        'seo_description' => "Освобождение от уплаты  транспортного налога организаций — резидентов особой экономической зоны  на десять налоговых периодов, начиная с налогового периода, в котором была осуществлена регистрация транспортного средства в порядке, установленном законодательством Российской Федерации.",
    ],

    [
        'title' => "Предоставление льготы по земельному налогу для резидентов ОЭЗ «Третий полюс»",
        'title_en' => "Provision of land tax benefits for residents of the SEZ «Third Pole»",
        'type' => "Резидентам ОЭЗ «Третий полюс»",
        //'img' => "",
        //'inner_img' => "",
        //'inner_img_en' => "",
        'short_description' => "",
        //'short_description_en' =>"",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Предоставление льготы по земельному налогу для резидентов ОЭЗ «Третий полюс»",
        'seo_description' => "Пунктом 9 статьи 395 Налогового кодекса предусмотрено освобождение от уплаты земельного налога организаций — резидентов особой экономической зоны (далее — ОЭЗ)",
    ],

    [
        'title' => "Льгота по налогу на прибыль для резидентов ОЭЗ «Третий полюс»",
        'title_en' => "Income tax benefit for residents of the SEZ «Third Pole»",
        'type' => "Резидентам ОЭЗ «Третий полюс»",
        //'img' => "",
        //'inner_img' => "",
        //'inner_img_en' => "",
        'short_description' => "",
        //'short_description_en' =>"",
        'description' => "description.html",
        'description_en' => "en_description.html",
        'seo_title' =>"Льгота по налогу на прибыль для резидентов ОЭЗ «Третий полюс»",
        'seo_description' => "Освобождение от уплаты  налога на имущество организаций — резидентов особой экономической зоны в течение десяти лет с месяца, следующего за месяцем постановки на учет имущества.",
    ],

];
