<?php
$support_measures = [
    [
    'title' => "Льгота по налогу на имущество организаций",
    //'title_en' => "",
    'type' => "Меры поддержки инвестора",
    'folder'=>"Corporate_property_tax_benefit",
    'img' => "e12fjw9bpmk-159ceb12.webp",
    'inner_img' => "nalog-na-im-vo-57a71c6f.webp",
    //'inner_img_en' => "",
    'short_description' => "short_description.html",
    //'short_description_en' =>"",
    'description' => "description.html",
    //'description_en' => "",
    'seo_title' =>"Льгота по налогу на имущество организаций для юридических лиц, реализующих инвестиционные проекты в режиме наибольшего благоприятствования",
    'seo_description' => "Льготы по налогу на имущество организаций в Курской области предоставляются в соответствии с законодательством Российской Федерации и региональными",
    ],
    [
        'title' => "Предоставление пониженных ставок по налогу на прибыль организации",
        //'title_en' => "",
        'type' => "Меры поддержки инвестора",
        'img' => "nkspwim0nvq-605263a4.webp",
        'inner_img' => "nalog-na-pribyl.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Предоставление пониженных ставок по налогу на прибыль организации",
        'seo_description' => "В Курской области, как и в большинстве регионов России, действуют пониженные ставки по налогу на прибыль организаций. Это означает, что вместо стандартной",
    ],
    [
        'title' => "Предоставление льготы по налогу на имущество",
        //'title_en' => "",
        'type' => "Меры поддержки общие",
        'img' => "mi7xunlrujg-1d6e8a63.webp",
        'inner_img' => "nalog-na-im-vo.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Предоставление льготы по налогу на имущество",
        'seo_description' => "Предоставление льготы по налогу на имущество",
    ],
    [
        'title' => "Предоставление субсидий на возмещение процентов по кредитам",
        //'title_en' => "",
        'type' => "Меры поддержки общие",
        'img' => "sheto9r5ln0-611bbde3.webp",
        'inner_img' => "subsidii-na-vozmeshhenie-kreditov.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Предоставление субсидий на возмещение процентов по кредитам",
        'seo_description' => "В Курской области для инвесторов предусмотрены различные меры поддержки, включая предоставление субсидий на возмещение процентов по кредитам. Субсидии",
    ],
    [
        'title' => "Предоставление земельных участков на льготных условиях",
        //'title_en' => "",
        'type' => "Меры поддержки общие",
        'img' => "park-yubilejnyj-pyaterochka-a9a59151.webp",
        'inner_img' => "zemelnye-uchastki-350f6392.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Предоставление земельных участков на льготных условиях",
        'seo_description' => "В соответствии с положениями ст. 39.6 Земельного кодекса РФ был принят закон Курской области от 22 июня 2015 года № 58-ЗКО «Об установлении критериев, которым",
    ],
    [
        'title' => "Инвестиционный налоговый вычет",
        //'title_en' => "",
        'type' => "Меры поддержки общие",
        'img' => "jpvxudpuoyw-84b71b7a.webp",
        'inner_img' => "investiczionnyj-nalogovyj-vychet.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Инвестиционный налоговый вычет",
        'seo_description' => "Инвестиционный налоговый вычет",
    ],
    [
        'title' => "Инвестиционный фонд Курской области",
        //'title_en' => "",
        'type' => "Меры поддержки общие",
        'img' => "lry7nbswuuk-3fe55a0a.webp",
        'inner_img' => "investiczionnyj-fond-kursk.webp",
        //'inner_img_en' => "",
        'short_description' => "short_description.html",
        //'short_description_en' =>"",
        'description' => "description.html",
        //'description_en' => "",
        'seo_title' =>"Инвестиционный фонд Курской области",
        'seo_description' => "Инвестиционный фонд Курской области — это организация, которая занимается привлечением инвестиций в регион. Он был создан для того, чтобы помочь развитию",
    ],

];
